@startuml
actor       User                      as Foo1
boundary    UserInterface             as Foo2
control     ReviewManagerController   as Foo3
database    Database                  as Foo4


Foo1 -> Foo2 : enter address/ use GPS
Foo2 -> Foo3 : send search request
Foo3 -> Foo4 : fetch carpark
Foo4 -> Foo3 : return search results
Foo3 -> Foo2 : display results

Foo1 -> Foo2 : select carpark to review
Foo2 -> Foo3 : send request
Foo3 -> Foo2 : display review page

Foo1 -> Foo2 : enter review
Foo2 -> Foo3 : send reviewRequest
Foo3 -> Foo4 : add reviewRequest

@enduml
